### ISSUE TITLE
PLEASE FIX

### ISSUE THREAD

**Issue by AirLeMineral** [CHOK9938/CubeCraft-Scoreboard#1]
I've added the logo in the texture file, then made the scorehud format like this
server-name:
-  "cubecraft.sb.logo"

but the image becomes black and purple squares
please fix it, thanks :D

**Comment by CHOK9938** [comment]
The size of the inserted image may be too large or not match the original.

**Comment by AirLeMineral** [comment]
> The size of the inserted image may be too large or not match the original.

Size image? Or size like 15kb
I've made a logo with the same size 381 x 128 px
